logging:
  level:
    ROOT: INFO
    com.test.af: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
application:
  security:
    cors:
      allowed-origins:
        - http://localhost:4200
        - http://localhost:9090
server:
  port: 9090